title: Reassume
resume:
  name: 辛正宝
  jobtitle: 个人简历
  contact:
    - icon: fa-external-link
      text: https://ronaldoxzb.com
    - icon: fa-envelope
      text: queenxzb@gmail.com
    - icon: fa-phone-square
      text: 17767711318
  profiles:
    - icon: fa-github
      text: https://github.com/ronaldoxzb
      link: https://github.com/ronaldoxzb
  overview:
    一年多团队管理经验，可独立开发大型中台项目，多个vue组件化、node服务开发经验。善于沟通、协调，有较强的组织能力与团队精神。严谨的代码习惯及性能优化的意识，深入了解业务，坚决不做前端工具人。
    # level: beginner, intermediate, advanced, master
  skills:
    - level: master
      levelname: 精通
      items:
        [
          javascript,
          es6,
          vue.js,
          钉钉/微信小程序,
          uni-app,
          vue-cli3,
          element-ui,
          ant-design,
        ]
    - level: advanced
      levelname: 熟练掌握
      items:
        [
          html,
          css,
          node.js,
          egg.js,
          redis,
          sequelize,
          nginx,
          docker,
          docker-compose,
        ]
    - level: intermediate
      levelname: 熟悉
      items: [react.js, webpack, ts, nacos, midway.js, rabbitmq, taro.js]
  experience:
    - position: 前端开发leader
      duration: 2020.3 - 2021.3
      company: Babycare(夕尔控股)
      # website: website.com
      description: 一：负责公司<b>核心产品框架设计、核心代码编写、wiki知识库维护</b> </p>二：<b>制定团队编码规范和git分支提交规范</b>，开发提升工作效率的版本发布脚本工具、node服务等</p>三：理解项目需求，拆分需求，分配开发任务，跟进项目开发进度，协调各部门，配合项目发布事宜等</p>四：制定团队绩效标准，做好团队建设，技术赋能业务，凸显技术价值
      hilights:
        [
          构建公司基于<b>vue.js的通用框架</b>、<b>uni-app（vue-cli）</b>的通用小程序框架、<b>egg服务端</b>通用模版,
          <b>完成xier-cli脚手架工具。xier-upload、xier-log、xier-search等通用组件，并上传至内部nexus 提升开发效率</b>,
          <b>完成gitlab webhooks 调用node服务自动merge代码，完成油猴脚本，根据禅道迭代版本自动合并release分支，提高生产力</b>,
          制定前端开发规范并要求组内成员践行，配置通用eslint代码规范，制定git分支规范维护好各环境分支,
          定期开展组内技术分享，促进团队成长，关注前端前沿技术，通过新技术赋能团队和业务,
          评审项目需求，并将需求拆解，合理安排开发任务，做好协调沟通，保证项目按时迭代，高度配合相关部门完成项目的发布及上线,
        ]
    - position: 前端开发工程师
      duration: 2017.3 - 2020.3
      company: 杭州千之软件技术有限公司
      # website: website.com
      description: 一：负责公司钉钉小程序框架设计、代码编写</p>二：配合后台完成数据接口设计、接口对接及页面数据渲染</p>三：参与后台接口编写、脚本编写
      hilights:
        [
          工作安排高效、高质地完成代码编写，确保符合规范的前端代码规范,
          <b>负责公司H5和微信小程序，钉钉小程序等前端⻚面架构的搭建及开发</b>,
          与后端开发团队紧密配合，确保代码有效对接，优化网站前端性能,
          解决项目开发过程中遇到的技术和业务难题，高质量完成web前端开发工作,
        ]
    - position: 前端开发工程师
      duration: 2016.7-2017.2
      company: accenture埃森哲信息技术（大连）有限公司
      # website: website.com
      description: 一：学习并熟悉软件开发流程，学习沟通技巧，完成主管所安排开发任务，<b>主要基于 adobe aem开发</b>
      hilights:
        [
          学习⽇常⼯作中的主要应⽤技术并对了解项⽬的整体流程,
          根据技术⽂档中详细描述，完成软件功能的开发，并尝试理解为什么要如此实现,
          在项⽬的开发过程中及开发后期整理相关的⽂档，做好⼯作记录，并按公司规定填写相关材料,
        ]
      # Education
  education:
    - institution: ⻓春⼯业⼤学—数字媒体技术（全日制本科）
      duration: 2012.9 - 2016.06
      location: 吉林省，⻓春市
  # Showcase your work
  projects:
    - title: oms业务中台（订单管理系统）
      description: <span>从0搭建公司订单管理系统，</span>选择vue.js为基本框架，搭配使用vue-router，vuex，axios等插件，ant-design组件库二次封装进行开发。</p>接入钉钉sso扫码登录，期间完成<b>系统菜单/按钮等权限的控制，</b>完成axios拦截器的单例封装，</p>本地开发多服务配置，及<b>webpack优化</b></p>完成字典接口vuex的缓存配置，mixins混入常用变量及方法</p>完成仓库、店铺、商品选择等业务组件，异步导出、同步导入、精简搜索、等公共组件的封装</p>完成b2c、b2b订单管理，完成库存管理、退换货管理、调拨管理，渠道管理，采购等核心模块的功能开发</p>经过团队5人半年开发，实现整个系统功能，替换原有巨益oms，为公司节省成本，实现更多个性化的定制功能，系统已经历两年6.18和双11全渠道订单域流程管理</p>
      duration: 2020.4 - 2020.10
      contribution: 负责人 + 核心开发
    - title: H5微信公众号品牌推广全栈项目
      description: 双11机制传播营销项目，通过用户分享h5页面的方式达到促销商品的目的 使用<b>egg.js + mysql(sequelize) + nunjucks（模版引擎）渲染vue页面</b></p>通过<b>定时任务获取access_token</b>，通过access_token获取jsapi_ticket。jsapi_ticket及随机生成的字符串、时间戳，再加上需要授权的页面地址url来实现微信jssdk的调用</p>封装common-service层，实现通用的查询、分页查询、新增、批量新增、删除等操作、orm工具建表等</p>封装<b>错误处理、分页、ip黑名单配置等中间件</b>，系统加入埋点，实现统计，<b>jmeter压测单节点2000+并发量，</b>k8s部署四节点，运行稳定</p>公司<b>node技术的沉淀，成为公司egg通用服务框架，积累了前端服务经验</b></p><b>h5总pv25.2万+，uv17万+，前两日达到16万pv+，</b>共被分享朋友圈2192次，被转发给朋友7811次。据业务部门统计（飞鸽）， 此项目引流进店访客<b>19.2万+，成交额270.9万，下单转化率达14.1%，平均客单价在157元，roi达到1:70，</b>受到公司品牌部好评，其他业务部也因此效仿做此种推广方式。
      duration: 2021.10 - 2021.11
      contribution: 负责人  + 核心开发
    - title: 权限管理系统
      description: 为了实现公司全部系统的菜单权限控制，<b>独立负责系统开发，搭建统一的菜单授权系统，</b>通过创建应用（管理系统），用户，并对用户赋予角色，对角色赋予菜单权限实现其他各系统的菜单/按钮权限控制</p>搭配使用vue-router，vuex，axios等相关插件，element-ui组件库二次封装进行开发，接入钉钉sso扫码登录，期间完成系统路由菜单/按钮等权限的控制，完成axios拦截器的全局配置，常用工具函数的封装，toTree、dfs、bfs等，封装日志、应用选择、oss上传组件等</p>完成用户管理，角色管理，菜单管理，应用管理，同步菜单等模块。为了实现不同环境菜单的同步，通过对比debug与test环境菜单数据, 查找新增菜单或更新的菜单，循环调用新增接口进行同步</p>一个月完成上线，到目前<b>公司20多个后台管理系统都已接入这套权限，成功支撑起公司员工账号系统权限的问题。</b></p>
      duration: 2021.2 - 2021.4
      contribution: 负责人 + 独立开发
    - title: 内购小程序商城
      description: 作为公司发放福利的一种方式，开发内部小程序商城可供内购，<b>一期使用钉钉原生小程序开发，二期考虑到项目的维护问题，使用uni-app重构</b></p>期间，搭建基于vue-cli 的开发环境，并可编译到h5,mp-alipay(钉钉平台),mp-weixin等平台，封装公共组件，mixins混入常用变量及方法等常规操作。</p><b>通过注册全局监听事件解决登录失效问题</b>, 编写购物车，订单，支付，识别淘口令等核心模块代码。</p>经过两期的迭代，统一vue技术栈，方便日后维护。已成为<b>公司内部使用频率最高的小程序，平均日活1000+</b></p>
      duration: 2020.6 - 2020.8
      contribution: 负责人  + 核心开发
    - title: <a href="https://ronaldoxzb.cn">egg-spider 个人项目</a>
      description: egg.js(jwt) + mysql(sequelize) + redis + docker + docker-compose + nginx + vue + element-ui 全栈获取全国省市区数据，前后端分离【工具】项目，实现https一键部署。用户注册登录（jwt）</p>统计局网页省市区数据的爬取，部门省份数据量很大，加入redis提高接口响应速度</p>实现资源的监控（node os),羽雀api的调用,邮件的发送基于(smtp.qq.com)</p>docker-compose部署前后端，购买域名获取证书，实现nginx代理实现https服务</p><b>熟悉整个web项目的docker发布流程，独立完成整个项目的开发及部署，项目预览地址见标题 账号：admin 密码：ronaldoxzb</b><p>
      duration: 2021.7 - 2021.8
      contribution: 独立开发
  # Langguages Known
  # proficiency: beginner, intermediate, advanced, master, fluent, native speaker
  languages:
    - name: 2021年获得PMI项目管理职业资格认证（PMP证书）
    - name: 2020年获得国家初级育婴师证
    - name: 2019年获得杭州千之软件技术有限公司年度优秀员⼯奖
    - name: 2016年在埃森哲（Digital部⻔）年会中演唱歌曲获得⼆等奖
    - name: 2015年获得“⼤学⽣创新创业⼤赛”优秀奖。
    - name: 2014年作为院⽂艺部部⻓成功策划“舞动⻘春”⽐赛，丰富了学⽣的课余⽣活。
    - name: 2013年全国“⼤学⽣⼴告设计⼤赛”获得三等奖。
    - name: 2013年届新⽣⼊学军训合唱⽐赛，指导本院学⽣获得⼆等奖。
