title: Reassume
resume:
  name: 辛正宝
  jobtitle: 个人简历
  location:
    - key: address
      value: 高润云杉郡
    - key: postalCode
      value: '310000'
    - key: city
      value: 杭州
    - key: region
      value: 浦沿/滨江
    - key: countryCode
      value:  中国🇨🇳
  contact:
    - icon: fa-envelope
      text: queenxzb@163.com
    - icon: fa-phone-square
      text: 17767711318
  profiles:
    - icon: fa-github
      text: https://github.com/ronaldoxzb
      link: https://github.com/ronaldoxzb
  overview: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      # level: beginner, intermediate, advanced, master
  skills:
    - title: Skill Group 1
      level: advanced
      items: [Lorem, Ipsum, Dolor, Sit, Amet]
    - title: Skill Group 2
      level: intermediate
      items: [Consectetur, Adipiscing, Elit]
    - title: Skill Group 3
      level: beginner
      items: [Sed do, Eiusmod, Tempor, Incididunt]
  experience:
    - position: Job Title 1
      duration: Apr 2016 - Now
      company: Your 1st, Inc.
      website: website.com
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      hilights: [
        Optimized an algorithm that holds the current world record for Weisman Scores,
        Hilight 2,
        Hilight 3,
      ]
    - position: Job Title 2
      duration: Apr 2013 - Mar 2016
      company: Your 2nd, Inc.
      website: website.com
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      hilights: [
        Hilight 1,
        Optimized an algorithm that holds the current world record for Weisman Scores
      ]
    - position: Job Title 3
      duration: Dec 2011 - Mar 2012
      company: Your 3rd Co, Ltd.
      website: website.com
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  
      # Education
  education:
    - institution: Your First University
      course: Masters Information Technology
      duration: Jul 2011 - Dec 2012
      location: Consectetur adipiscing elit
      major: Lorem ipsum dolor sit amet
    - institution: Your Second University
      course: Masters Information Technology
      duration: Aug 2007 - Jun 2011
      location: Ut enim ad minim veniam
      major: Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
# Showcase your work
  projects:
  - title: Project Name 1
    description: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    duration: Jul 2011 - Dec 2012
    contribution: Contributor.
  - title: Project Name 2
    description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    duration: Aug 2007 - Jun 2011
    contribution: Creator and maintainer.
# Langguages Known 
# proficiency: beginner, intermediate, advanced, master, fluent, native speaker
  languages:
  - name: English
    proficiency: fluent
  - name: Hindi
    proficiency: native speaker
  - name: Hindi
    proficiency: fluent